package com.plugin.ezetap.sdk.eze_sdk_flutter

/**
@author TIJO THOMAS
@since 10/11/22
 */
object EzeConstants {
    const val INITIALIZE_REQUEST_CODE = 1001
    const val PREPARE_DEVICE_REQUEST_CODE = 1002
    const val CARD_INFO_REQUEST_CODE = 1003
    const val SEND_RECEIPT_REQUEST_CODE = 1005
    const val SERVICE_REQUEST_CODE = 1008
    const val SEARCH_TRANSACTION_REQUEST_CODE = 1012
    const val GET_TRANSACTION_REQUEST_CODE = 1013
    const val CHECK_INCOMPLETE_TRANSACTION_REQUEST_CODE = 1014
    const val VOID_TRANSACTION_REQUEST_CODE = 1015
    const val ATTACH_SIGNATURE_REQUEST_CODE = 1016
    const val GENERIC_TRANSACTION_REQUEST_CODE = 1019
    const val BRAND_EMI_TRANSACTION_REQUEST_CODE = 1021
    const val NORMAL_EMI_TRANSACTION_REQUEST_CODE = 1022
    const val PRINT_RECEIPT_REQUEST_CODE = 1023
    const val PRINT_BITMAP_REQUEST_CODE = 1024
    const val CLOSE_SESSION_REQUEST_CODE = 1025
    const val PRE_AUTH_REQUEST_CODE = 1027
    const val CONFIRM_PRE_AUTH_REQUEST_CODE = 1028
    const val RELEASE_PRE_AUTH_REQUEST_CODE = 1029
    const val STOP_PAYMENT_REQUEST_CODE = 1030
    const val SCAN_BARCODE = 1031
    const val GET_CARD_INFO = 1032
    const val GET_LOYALTY_CARD_INFO = 1033
    const val WALLET_TRANSACTION = 1034
    const val CHEQUE_TRANSACTION = 1035
    const val CARD_TRANSACTION = 1036
    const val CASH_TRANSACTION = 1037
    const val REMOTE_TRANSACTION = 1038
    const val DISPLAY_TRANSACTION_HISTORY = 1039
    const val UPI_TRANSACTION = 1040
    const val QR_CODE_TRANSACTION = 1041
    const val REFUND_TRANSACTION = 1042
    const val CHECK_FOR_UPDATES = 1043
}